### PR TITLE
use pure code instead of xib file, allow using with pure code so the storyboard is not necessary

### PR DESCRIPTION
**Pull request by gonghao**

### CODE REVIEW

**Comment by MrPans** [comment]
Good job bro! Now we can use PSCarouselView both with **Storyboard** and **Pure Code**.

The last one thing is give it a `NS_DESIGNATED_INITIALIZER`.I'll merge this PR later,and add NS_DESIGNATED_INITIALIZER.

**Comment by gonghao** [comment]
@DeveloperPans I don't know is it OK to add `NS_DESIGNATED_INITIALIZER` like [a882ab1](https://github.com/DeveloperPans/PSCarouselView/pull/8/commits/a882ab1f3dec45aad0604233e3296d1359f5256e).

Please review. Thanks.

**Comment by MrPans** [comment]
@gonghao nope. we shouldn't make `UICollectionViewLayout` API public,because it will be `FlowLayout` forever.

Change 

``` objective-c

- (instancetype)initWithFrame:(CGRect)frame collectionViewLayout:(UICollectionViewLayout *)layout NS_DESIGNATED_INITIALIZER;

```

to

``` objective-c
- (instancetype)initWithFrame:(CGRect)frame NS_DESIGNATED_INITIALIZER;

```

and override all super designated initializer is the correct way.

BTW, implement cell both with pure code and xib are ok. it won't have any difference for users. 
I prefer xib and wanna keep it. : )

**Comment by gonghao** [comment]
@DeveloperPans Yes, both pure code and xib are ok, but I think the situation here is too simple, so the pure code is enough. And with pure code, it also helps to reduce file numbers in project and reduce a nib IO. So I prefer to use pure code in such situation.

**Comment by gonghao** [comment]
I've checked some articles about the `NS_DESIGNATED_INITIALIZER` and override the superclass's `NS_DESIGNATED_INITIALIZER`

And I've made some modifications to fix some warnings in Xcode 7

http://stackoverflow.com/questions/29639040/warning-method-override-for-designated-initializer
https://github.com/pinterest/PINCache/pull/25

**Comment by MrPans** [comment]
cool. thanks, @gonghao

**Comment by gonghao** [comment]
:beers: @DeveloperPans

**Pull request merged**
